# These are supported funding platforms

github: mqxod       # Replace with your GitHub username if you enable GitHub Sponsors
buy_me_a_coffee: maqsood421
ko_fi: maqsood421
patreon: maqsood421
open_collective: typecert
custom: ["https://www.paypal.me/maqsood421"]
